name: 清除工作流日志
run-name: ${{ github.actor }} 正在执行清理
on:
  workflow_dispatch:
    inputs:
      days:
        description: '每个工作流保留日志的天数'
        required: true
        default: '0.2'
      minimum_runs:
        description: '每个工作流至少保留的日志数量'
        required: true
        default: '1'
      delete_workflow_pattern:
        description: '目标工作流的名称或文件名（留空则处理全部工作流）'
        required: false
      delete_workflow_by_state_pattern:
        description: '按状态筛选工作流'
        required: true
        default: "所有状态（ALL）"
        type: choice
        options:
          - "所有状态（ALL）"
          - "活跃状态（active）"
          - "已删除（deleted）"
          - "因不活跃禁用（disabled_inactivity）"
          - "手动禁用（disabled_manually）"
      delete_run_by_conclusion_pattern:
        description: '按执行结果筛选要删除的日志'
        required: true
        default: "全部结果（ALL）"
        type: choice
        options:
          - "全部结果（ALL）"
          - "仅失败：action_required,cancelled,failure,skipped"
          - action_required
          - cancelled
          - failure
          - skipped
          - success
      dry_run:
        description: '模拟运行（不会实际删除）'
        required: false

  schedule:
    - cron: '30 21 */3 * *'

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 执行日志清理
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days || 0.2 }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs || 1 }}
          delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern || '' }}
          delete_workflow_by_state_pattern: >-
            ${{ 
              github.event.inputs.delete_workflow_by_state_pattern 
              | replace('所有状态（ALL）', 'ALL') 
              | replace('活跃状态（active）', 'active') 
              | replace('已删除（deleted）', 'deleted') 
              | replace('因不活跃禁用（disabled_inactivity）', 'disabled_inactivity') 
              | replace('手动禁用（disabled_manually）', 'disabled_manually') 
            }}
          delete_run_by_conclusion_pattern: >-
            ${{ 
              startsWith(github.event.inputs.delete_run_by_conclusion_pattern, '仅失败：') 
              && 'action_required,cancelled,failure,skipped' 
              || (github.event.inputs.delete_run_by_conclusion_pattern || 'ALL') 
            }}
          dry_run: ${{ github.event.inputs.dry_run || false }}
