name: 修改socks5节点格式
run-name: ${{ github.actor }} 正在修改socks5节点格式
on:
#  push:
#    branches:
#      - master
#    paths:
#      - 'script/**'
  schedule:
#    - cron: '0 0,4,8,12,16,20 * * *' # 北京时间4 8 12 16 20 24 每四个小时整点运行
#    - cron: '5 23 */1 * *' # 北京时间七点抓取节点
    - cron: '*/30 * * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  clean_and_script:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRETS_TOKEN }}
      REPO: ${{ secrets.REPO }}
      DEBUG_MODE: 0
    steps:
  
      - name: 迁出代码
        uses: actions/checkout@v4

      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
  
      - name: 获取节点
        run: |
          curl -L -o ./socks5.txt https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5.txt
        shell: bash
      - name: 修改节点
        run: |
          grep 'US' ./socks5.txt | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+' | sed 's/^/socks5:\/\//' > ./socks5_temp.txt && mv ./socks5_temp.txt ./socks5.txt
        shell: bash
        
      - name: 对比仓库
        run: |
          git config --local user.email "932624033@qq.com"
          git config --local user.name "yyyr-otz"
          git add -A ./socks5.txt
          git diff-index --quiet HEAD || (git commit -a -m "🛒 socks5 🕕 $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M %Z')" --allow-empty)
#         # git commit -am "节点资源更新 $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M %Z')"

      - name: 推送更改
        uses: ad-m/github-push-action@v0.6.0
        with: 
          github_token: ${{ secrets.ACTIONS_SECRETS_TOKEN }}
          branch: master
